package com.github.naz013.logic.quickadd.vocabulary

/** Tier 1 launch languages (see REM-1221): en, es, fr, de, pt, it - chosen because they share
 * enough grammatical structure (space-tokenized, Latin alphabet, preposition-based) for one
 * regex skeleton to cover all of them via these word tables alone. */
object QuickAddVocabularies {

  val english = QuickAddVocabulary(
    languageTag = "en",
    everyWords = listOf("every", "each"),
    dailyUnitWords = listOf("day", "days"),
    weeklyUnitWords = listOf("week", "weeks"),
    monthlyUnitWords = listOf("month", "months"),
    yearlyUnitWords = listOf("year", "years"),
    dailyAdverbs = listOf("daily"),
    weeklyAdverbs = listOf("weekly"),
    monthlyAdverbs = listOf("monthly"),
    yearlyAdverbs = listOf("yearly", "annually"),
    workdayWords = listOf("weekday", "weekdays"),
    ordinalSuffixRegex = "st|nd|rd|th",
    todayWords = listOf("today"),
    tomorrowWords = listOf("tomorrow"),
    nextWords = listOf("next"),
    onWords = listOf("on"),
    atWords = listOf("at"),
    amWords = listOf("am", "a.m.", "a.m"),
    pmWords = listOf("pm", "p.m.", "p.m"),
    noonWords = listOf("noon", "midday"),
    midnightWords = listOf("midnight"),
    timeUnitWords = listOf("o'clock", "oclock"),
    dateOrder = DateOrder.MONTH_DAY,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("on", "at", "for", "to"),
  )

  /** "mañana" means both "tomorrow" and "morning" in Spanish; treated as "tomorrow" here since
   * that's the far more common quick-add phrasing - a known v1 ambiguity. */
  val spanish = QuickAddVocabulary(
    languageTag = "es",
    everyWords = listOf("cada", "todos los", "todas las"),
    dailyUnitWords = listOf("dia", "dias", "día", "días"),
    weeklyUnitWords = listOf("semana", "semanas"),
    monthlyUnitWords = listOf("mes", "meses"),
    yearlyUnitWords = listOf("ano", "anos", "año", "años"),
    dailyAdverbs = listOf("diariamente", "a diario"),
    weeklyAdverbs = listOf("semanalmente"),
    monthlyAdverbs = listOf("mensualmente"),
    yearlyAdverbs = listOf("anualmente"),
    workdayWords = listOf("dia laborable", "dias laborables", "día laborable", "días laborables"),
    ordinalSuffixRegex = "º|ª",
    todayWords = listOf("hoy"),
    tomorrowWords = listOf("manana", "mañana"),
    nextWords = listOf("proximo", "proxima", "próximo", "próxima"),
    onWords = listOf("el", "la"),
    atWords = listOf("a las", "a la"),
    amWords = listOf("am", "a.m.", "de la manana", "de la mañana"),
    pmWords = listOf("pm", "p.m.", "de la tarde", "de la noche"),
    noonWords = listOf("mediodia", "mediodía"),
    midnightWords = listOf("medianoche"),
    timeUnitWords = listOf("horas", "hora"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = listOf("de"),
    connectorWords = listOf("el", "la", "a", "para"),
  )

  val french = QuickAddVocabulary(
    languageTag = "fr",
    everyWords = listOf("chaque", "tous les", "toutes les"),
    dailyUnitWords = listOf("jour", "jours"),
    weeklyUnitWords = listOf("semaine", "semaines"),
    monthlyUnitWords = listOf("mois"),
    yearlyUnitWords = listOf("an", "ans", "annee", "annees", "année", "années"),
    dailyAdverbs = listOf("quotidiennement"),
    weeklyAdverbs = listOf("hebdomadairement"),
    monthlyAdverbs = listOf("mensuellement"),
    yearlyAdverbs = listOf("annuellement"),
    workdayWords = listOf("jour ouvre", "jours ouvres", "jour ouvré", "jours ouvrés"),
    ordinalSuffixRegex = "er|eme|ème|e",
    todayWords = listOf("aujourd'hui", "aujourdhui"),
    tomorrowWords = listOf("demain"),
    nextWords = listOf("prochain", "prochaine"),
    onWords = listOf("le", "la"),
    // Deliberately just "à" (accented), not bare "a" - the latter is French's extremely common
    // "has" verb form (il/elle a), which would false-positive-match all over ordinary text.
    atWords = listOf("à"),
    amWords = listOf("am", "du matin"),
    pmWords = listOf("pm", "de l'apres-midi", "de l'après-midi", "du soir"),
    noonWords = listOf("midi"),
    midnightWords = listOf("minuit"),
    timeUnitWords = listOf("heures", "heure", "h"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("le", "la", "à", "pour"),
  )

  /** "morgen" means both "tomorrow" and "morning" in German; treated as "tomorrow" here, same
   * known v1 ambiguity as Spanish "mañana". */
  val german = QuickAddVocabulary(
    languageTag = "de",
    everyWords = listOf("jeden", "jede", "jedes", "alle"),
    dailyUnitWords = listOf("tag", "tage"),
    weeklyUnitWords = listOf("woche", "wochen"),
    monthlyUnitWords = listOf("monat", "monate"),
    yearlyUnitWords = listOf("jahr", "jahre"),
    dailyAdverbs = listOf("taglich", "täglich"),
    weeklyAdverbs = listOf("wochentlich", "wöchentlich"),
    monthlyAdverbs = listOf("monatlich"),
    yearlyAdverbs = listOf("jahrlich", "jährlich"),
    workdayWords = listOf("wochentag", "wochentage"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("heute"),
    tomorrowWords = listOf("morgen"),
    nextWords = listOf("nachsten", "nachste", "nächsten", "nächste"),
    onWords = listOf("am"),
    atWords = listOf("um"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("mittag", "mittags"),
    midnightWords = listOf("mitternacht"),
    timeUnitWords = listOf("uhr"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("am", "um", "fur", "für"),
  )

  val portuguese = QuickAddVocabulary(
    languageTag = "pt",
    everyWords = listOf("todo", "toda", "todos os", "todas as", "cada"),
    dailyUnitWords = listOf("dia", "dias"),
    weeklyUnitWords = listOf("semana", "semanas"),
    monthlyUnitWords = listOf("mes", "meses", "mês"),
    yearlyUnitWords = listOf("ano", "anos"),
    dailyAdverbs = listOf("diariamente"),
    weeklyAdverbs = listOf("semanalmente"),
    monthlyAdverbs = listOf("mensalmente"),
    yearlyAdverbs = listOf("anualmente"),
    workdayWords = listOf("dia util", "dias uteis", "dia útil", "dias úteis"),
    ordinalSuffixRegex = "º|ª",
    todayWords = listOf("hoje"),
    tomorrowWords = listOf("amanha", "amanhã"),
    nextWords = listOf("proximo", "proxima", "próximo", "próxima"),
    onWords = listOf("no", "na"),
    // Deliberately just "às" (accented contraction), not bare "as" - the latter is Portuguese's
    // common feminine plural article ("the"), which would false-positive-match constantly.
    atWords = listOf("às"),
    amWords = listOf("am", "da manha", "da manhã"),
    pmWords = listOf("pm", "da tarde", "da noite"),
    noonWords = listOf("meio-dia", "meio dia"),
    midnightWords = listOf("meia-noite", "meia noite"),
    timeUnitWords = listOf("horas", "hora"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = listOf("de"),
    connectorWords = listOf("no", "na", "às", "para"),
  )

  val italian = QuickAddVocabulary(
    languageTag = "it",
    everyWords = listOf("ogni", "tutti i", "tutte le"),
    dailyUnitWords = listOf("giorno", "giorni"),
    weeklyUnitWords = listOf("settimana", "settimane"),
    monthlyUnitWords = listOf("mese", "mesi"),
    yearlyUnitWords = listOf("anno", "anni"),
    dailyAdverbs = listOf("giornalmente", "quotidianamente"),
    weeklyAdverbs = listOf("settimanalmente"),
    monthlyAdverbs = listOf("mensilmente"),
    yearlyAdverbs = listOf("annualmente"),
    workdayWords = listOf("giorno feriale", "giorni feriali"),
    ordinalSuffixRegex = "°|ª",
    todayWords = listOf("oggi"),
    tomorrowWords = listOf("domani"),
    nextWords = listOf("prossimo", "prossima"),
    onWords = listOf("il", "la"),
    atWords = listOf("alle", "alla"),
    amWords = listOf("am", "di mattina"),
    pmWords = listOf("pm", "del pomeriggio", "di sera"),
    noonWords = listOf("mezzogiorno"),
    midnightWords = listOf("mezzanotte"),
    timeUnitWords = listOf("ore", "ora"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("il", "la", "alle", "alla", "per"),
  )

  /** "morgen" means both "tomorrow" and "morning" in Dutch, same known ambiguity as German. */
  val dutch = QuickAddVocabulary(
    languageTag = "nl",
    everyWords = listOf("elke", "elk", "iedere", "ieder"),
    dailyUnitWords = listOf("dag", "dagen"),
    weeklyUnitWords = listOf("week", "weken"),
    monthlyUnitWords = listOf("maand", "maanden"),
    yearlyUnitWords = listOf("jaar", "jaren"),
    dailyAdverbs = listOf("dagelijks"),
    weeklyAdverbs = listOf("wekelijks"),
    monthlyAdverbs = listOf("maandelijks"),
    yearlyAdverbs = listOf("jaarlijks"),
    workdayWords = listOf("werkdag", "werkdagen"),
    ordinalSuffixRegex = "e",
    todayWords = listOf("vandaag"),
    tomorrowWords = listOf("morgen"),
    nextWords = listOf("volgende"),
    onWords = listOf("op"),
    atWords = listOf("om"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("middag"),
    midnightWords = listOf("middernacht"),
    timeUnitWords = listOf("uur"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("op", "om", "voor"),
  )

  val swedish = QuickAddVocabulary(
    languageTag = "sv",
    everyWords = listOf("varje"),
    dailyUnitWords = listOf("dag", "dagar"),
    weeklyUnitWords = listOf("vecka", "veckor"),
    monthlyUnitWords = listOf("manad", "manader", "månad", "månader"),
    yearlyUnitWords = listOf("ar", "år"),
    dailyAdverbs = listOf("dagligen"),
    weeklyAdverbs = listOf("veckovis"),
    monthlyAdverbs = listOf("manadsvis", "månadsvis"),
    yearlyAdverbs = listOf("arligen", "årligen"),
    workdayWords = listOf("vardag", "vardagar"),
    ordinalSuffixRegex = ":a|:e",
    todayWords = listOf("idag"),
    tomorrowWords = listOf("imorgon", "i morgon"),
    nextWords = listOf("nasta", "nästa"),
    onWords = listOf("pa", "på"),
    atWords = listOf("klockan", "kl"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("middag"),
    midnightWords = listOf("midnatt"),
    timeUnitWords = emptyList(),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("pa", "på", "for", "för"),
  )

  val danish = QuickAddVocabulary(
    languageTag = "da",
    everyWords = listOf("hver"),
    dailyUnitWords = listOf("dag", "dage"),
    weeklyUnitWords = listOf("uge", "uger"),
    monthlyUnitWords = listOf("maned", "maneder", "måned", "måneder"),
    yearlyUnitWords = listOf("ar", "år"),
    dailyAdverbs = listOf("dagligt"),
    weeklyAdverbs = listOf("ugentligt"),
    monthlyAdverbs = listOf("manedligt", "månedligt"),
    yearlyAdverbs = listOf("arligt", "årligt"),
    workdayWords = listOf("hverdag", "hverdage"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("i dag", "idag"),
    tomorrowWords = listOf("i morgen", "imorgen"),
    nextWords = listOf("neste", "næste"),
    onWords = listOf("pa", "på"),
    atWords = listOf("klokken", "kl"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("middag"),
    midnightWords = listOf("midnat"),
    timeUnitWords = emptyList(),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("pa", "på", "for"),
  )

  val norwegian = QuickAddVocabulary(
    languageTag = "nb",
    everyWords = listOf("hver", "hvert"),
    dailyUnitWords = listOf("dag", "dager"),
    weeklyUnitWords = listOf("uke", "uker"),
    monthlyUnitWords = listOf("maned", "maneder", "måned", "måneder"),
    yearlyUnitWords = listOf("ar", "år"),
    dailyAdverbs = listOf("daglig"),
    weeklyAdverbs = listOf("ukentlig"),
    monthlyAdverbs = listOf("manedlig", "månedlig"),
    yearlyAdverbs = listOf("arlig", "årlig"),
    workdayWords = listOf("hverdag", "hverdager"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("i dag", "idag"),
    tomorrowWords = listOf("i morgen", "imorgen"),
    nextWords = listOf("neste"),
    onWords = listOf("pa", "på"),
    atWords = listOf("klokken", "kl"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("middag"),
    midnightWords = listOf("midnatt"),
    timeUnitWords = emptyList(),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("pa", "på", "for"),
  )

  val polish = QuickAddVocabulary(
    languageTag = "pl",
    everyWords = listOf("co", "kazdy", "kazda", "kazde", "kazdego", "każdy", "każda", "każde", "każdego"),
    dailyUnitWords = listOf("dzien", "dni", "dzień"),
    weeklyUnitWords = listOf("tydzien", "tygodnie", "tygodni", "tydzień"),
    monthlyUnitWords = listOf("miesiac", "miesiace", "miesiecy", "miesiąc", "miesiące", "miesięcy"),
    yearlyUnitWords = listOf("rok", "lata", "lat"),
    dailyAdverbs = listOf("codziennie"),
    weeklyAdverbs = listOf("tygodniowo"),
    monthlyAdverbs = listOf("miesiecznie", "miesięcznie"),
    yearlyAdverbs = listOf("rocznie"),
    workdayWords = listOf("dzien roboczy", "dni robocze", "dzień roboczy"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("dzisiaj", "dzis", "dziś"),
    tomorrowWords = listOf("jutro"),
    nextWords =
    listOf("nastepny", "nastepna", "nastepne", "nastepnego", "następny", "następna", "następne", "następnego"),
    onWords = listOf("w"),
    atWords = listOf("o"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("poludnie", "południe"),
    midnightWords = listOf("polnoc", "północ"),
    timeUnitWords = emptyList(),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("w", "o", "na"),
  )

  val czech = QuickAddVocabulary(
    languageTag = "cs",
    everyWords = listOf("kazdy", "kazda", "kazde", "kazdeho", "každý", "každá", "každé", "každého"),
    dailyUnitWords = listOf("den", "dny", "dni"),
    weeklyUnitWords = listOf("tyden", "tydny", "tydnu", "týden", "týdny", "týdnů"),
    monthlyUnitWords = listOf("mesic", "mesice", "mesicu", "měsíc", "měsíce", "měsíců"),
    yearlyUnitWords = listOf("rok", "roky", "let"),
    dailyAdverbs = listOf("denne", "denně"),
    weeklyAdverbs = listOf("tydne", "týdně"),
    monthlyAdverbs = listOf("mesicne", "měsíčně"),
    yearlyAdverbs = listOf("rocne", "ročně"),
    workdayWords = listOf("pracovni den", "pracovni dny", "pracovní den", "pracovní dny"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("dnes"),
    tomorrowWords = listOf("zitra", "zítra"),
    nextWords = listOf("pristi", "dalsiho", "příští", "dalšího"),
    onWords = listOf("v"),
    atWords = listOf("v"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("poledne"),
    midnightWords = listOf("pulnoc", "půlnoc"),
    timeUnitWords = listOf("hodin", "hodinu", "hodiny"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("v", "na"),
  )

  /** "luni" means both "Monday" and "months" in Romanian - matching a weekday name is tried
   * before matching a recurrence unit word, so "every luni" resolves to "every Monday". */
  val romanian = QuickAddVocabulary(
    languageTag = "ro",
    everyWords = listOf("in fiecare", "în fiecare", "fiecare"),
    dailyUnitWords = listOf("zi", "zile"),
    weeklyUnitWords = listOf("saptamana", "saptamani", "săptămână", "săptămâni"),
    monthlyUnitWords = listOf("luna", "luni", "lună"),
    yearlyUnitWords = listOf("an", "ani"),
    dailyAdverbs = listOf("zilnic"),
    weeklyAdverbs = listOf("saptamanal", "săptămânal"),
    monthlyAdverbs = listOf("lunar"),
    yearlyAdverbs = listOf("anual"),
    workdayWords = listOf("zi lucratoare", "zile lucratoare", "zi lucrătoare", "zile lucrătoare"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("azi", "astazi", "astăzi"),
    tomorrowWords = listOf("maine", "mâine"),
    nextWords = listOf("urmatoarea", "urmatorul", "următoarea", "următorul"),
    onWords = listOf("in", "în"),
    atWords = listOf("la"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("pranz", "amiaza", "prânz", "amiază"),
    midnightWords = listOf("miezul noptii", "miezul nopții"),
    timeUnitWords = listOf("ora", "ore"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("in", "în", "la", "pentru"),
  )

  val ukrainian = QuickAddVocabulary(
    languageTag = "uk",
    everyWords = listOf("кожен", "кожна", "кожне", "кожного"),
    dailyUnitWords = listOf("день", "дні", "днів"),
    weeklyUnitWords = listOf("тиждень", "тижні", "тижнів"),
    monthlyUnitWords = listOf("місяць", "місяці", "місяців"),
    yearlyUnitWords = listOf("рік", "роки", "років"),
    dailyAdverbs = listOf("щодня", "щоденно"),
    weeklyAdverbs = listOf("щотижня", "щотижнево"),
    monthlyAdverbs = listOf("щомісяця", "щомісячно"),
    yearlyAdverbs = listOf("щороку", "щорічно"),
    workdayWords = listOf("робочий день", "робочі дні"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("сьогодні"),
    tomorrowWords = listOf("завтра"),
    nextWords = listOf("наступний", "наступна", "наступне", "наступного"),
    onWords = listOf("у", "в"),
    atWords = listOf("о", "в"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("полудень"),
    midnightWords = listOf("північ"),
    timeUnitWords = listOf("годині", "годин", "годину"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("у", "в", "о", "на"),
  )

  val russian = QuickAddVocabulary(
    languageTag = "ru",
    everyWords = listOf("каждый", "каждая", "каждое", "каждого"),
    dailyUnitWords = listOf("день", "дня", "дней"),
    weeklyUnitWords = listOf("неделя", "недели", "недель"),
    monthlyUnitWords = listOf("месяц", "месяца", "месяцев"),
    yearlyUnitWords = listOf("год", "года", "лет"),
    dailyAdverbs = listOf("ежедневно"),
    weeklyAdverbs = listOf("еженедельно"),
    monthlyAdverbs = listOf("ежемесячно"),
    yearlyAdverbs = listOf("ежегодно"),
    workdayWords = listOf("рабочий день", "рабочие дни"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("сегодня"),
    tomorrowWords = listOf("завтра"),
    nextWords = listOf("следующий", "следующая", "следующее", "следующего"),
    onWords = listOf("в", "во"),
    atWords = listOf("в", "во"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("полдень"),
    midnightWords = listOf("полночь"),
    timeUnitWords = listOf("часов", "час", "часа"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("в", "во", "на"),
  )

  val bulgarian = QuickAddVocabulary(
    languageTag = "bg",
    everyWords = listOf("всеки", "всяка", "всяко"),
    dailyUnitWords = listOf("ден", "дни"),
    weeklyUnitWords = listOf("седмица", "седмици"),
    monthlyUnitWords = listOf("месец", "месеца", "месеци"),
    yearlyUnitWords = listOf("година", "години"),
    dailyAdverbs = listOf("ежедневно"),
    weeklyAdverbs = listOf("седмично"),
    monthlyAdverbs = listOf("месечно"),
    yearlyAdverbs = listOf("годишно"),
    workdayWords = listOf("работен ден", "работни дни"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("днес"),
    tomorrowWords = listOf("утре"),
    nextWords = listOf("следващия", "следващият", "следващата"),
    onWords = listOf("в"),
    atWords = listOf("в"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("обяд"),
    midnightWords = listOf("полунощ"),
    timeUnitWords = listOf("часа", "часът"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("в", "на"),
  )

  val indonesian = QuickAddVocabulary(
    languageTag = "id",
    everyWords = listOf("setiap", "tiap"),
    dailyUnitWords = listOf("hari"),
    weeklyUnitWords = listOf("minggu"),
    monthlyUnitWords = listOf("bulan"),
    yearlyUnitWords = listOf("tahun"),
    dailyAdverbs = listOf("harian"),
    weeklyAdverbs = listOf("mingguan"),
    monthlyAdverbs = listOf("bulanan"),
    yearlyAdverbs = listOf("tahunan"),
    workdayWords = listOf("hari kerja"),
    ordinalSuffixRegex = "",
    todayWords = listOf("hari ini"),
    tomorrowWords = listOf("besok"),
    nextWords = listOf("berikutnya", "depan"),
    onWords = listOf("pada"),
    atWords = listOf("pukul", "jam"),
    amWords = listOf("pagi"),
    pmWords = listOf("siang", "sore", "malam"),
    noonWords = listOf("tengah hari"),
    midnightWords = listOf("tengah malam"),
    timeUnitWords = emptyList(),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("pada", "untuk"),
  )

  /** Vietnamese dates are conventionally written with a numbered month ("tháng 9"), not a locale
   * month name, so [dateOrder]'s month-name matching mostly won't fire here - a known v1 gap,
   * same spirit as other languages' documented limitations. */
  val vietnamese = QuickAddVocabulary(
    languageTag = "vi",
    everyWords = listOf("moi", "hang", "mỗi", "hàng"),
    dailyUnitWords = listOf("ngay", "ngày"),
    weeklyUnitWords = listOf("tuan", "tuần"),
    monthlyUnitWords = listOf("thang", "tháng"),
    yearlyUnitWords = listOf("nam", "năm"),
    dailyAdverbs = emptyList(),
    weeklyAdverbs = emptyList(),
    monthlyAdverbs = emptyList(),
    yearlyAdverbs = emptyList(),
    workdayWords = listOf("ngay lam viec", "ngày làm việc"),
    ordinalSuffixRegex = "",
    todayWords = listOf("hom nay", "hôm nay"),
    tomorrowWords = listOf("ngay mai", "ngày mai"),
    nextWords = listOf("toi", "sau", "tới"),
    onWords = listOf("vao", "vào"),
    atWords = listOf("luc", "lúc"),
    amWords = listOf("sang", "sáng"),
    pmWords = listOf("chieu", "toi", "chiều", "tối"),
    noonWords = listOf("trua", "trưa"),
    midnightWords = listOf("nua dem", "nửa đêm"),
    timeUnitWords = listOf("gio", "giờ"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("vao", "vào", "luc", "lúc", "cho"),
  )

  val turkish = QuickAddVocabulary(
    languageTag = "tr",
    everyWords = listOf("her"),
    dailyUnitWords = listOf("gun", "gün"),
    weeklyUnitWords = listOf("hafta"),
    monthlyUnitWords = listOf("ay"),
    yearlyUnitWords = listOf("yil", "sene", "yıl"),
    dailyAdverbs = listOf("gunluk", "günlük"),
    weeklyAdverbs = listOf("haftalik", "haftalık"),
    monthlyAdverbs = listOf("aylik", "aylık"),
    yearlyAdverbs = listOf("yillik", "yıllık"),
    workdayWords = listOf("is gunu", "iş günü"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("bugun", "bugün"),
    tomorrowWords = listOf("yarin", "yarın"),
    nextWords = listOf("gelecek", "onumuzdeki", "önümüzdeki"),
    onWords = emptyList(),
    atWords = listOf("saat"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("ogle", "öğle"),
    midnightWords = listOf("gece yarisi", "gece yarısı"),
    timeUnitWords = emptyList(),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("saat", "icin", "için"),
  )

  val arabic = QuickAddVocabulary(
    languageTag = "ar",
    everyWords = listOf("كل"),
    dailyUnitWords = listOf("يوم", "أيام"),
    weeklyUnitWords = listOf("أسبوع", "أسابيع"),
    monthlyUnitWords = listOf("شهر", "أشهر"),
    yearlyUnitWords = listOf("سنة", "سنوات"),
    dailyAdverbs = listOf("يوميا", "يومياً"),
    weeklyAdverbs = listOf("أسبوعيا", "أسبوعياً"),
    monthlyAdverbs = listOf("شهريا", "شهرياً"),
    yearlyAdverbs = listOf("سنويا", "سنوياً"),
    workdayWords = listOf("يوم عمل", "أيام العمل"),
    ordinalSuffixRegex = "",
    todayWords = listOf("اليوم"),
    tomorrowWords = listOf("غدا", "غداً", "بكرة"),
    nextWords = listOf("القادم", "القادمة"),
    onWords = listOf("يوم"),
    atWords = listOf("الساعة"),
    amWords = listOf("صباحا", "صباحاً"),
    pmWords = listOf("مساء", "مساءً", "ظهرا", "ظهراً"),
    noonWords = listOf("الظهر"),
    midnightWords = listOf("منتصف الليل"),
    timeUnitWords = emptyList(),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("يوم", "الساعة", "في"),
  )
}
