package com.github.naz013.logic.quickadd.vocabulary

/** Tier 1 launch languages (see REM-1221): en, es, fr, de, pt, it - chosen because they share
 * enough grammatical structure (space-tokenized, Latin alphabet, preposition-based) for one
 * regex skeleton to cover all of them via these word tables alone. */
object QuickAddVocabularies {

  val english = QuickAddVocabulary(
    languageTag = "en",
    everyWords = listOf("every", "each"),
    dailyUnitWords = listOf("day", "days"),
    weeklyUnitWords = listOf("week", "weeks"),
    monthlyUnitWords = listOf("month", "months"),
    yearlyUnitWords = listOf("year", "years"),
    dailyAdverbs = listOf("daily"),
    weeklyAdverbs = listOf("weekly"),
    monthlyAdverbs = listOf("monthly"),
    yearlyAdverbs = listOf("yearly", "annually"),
    workdayWords = listOf("weekday", "weekdays"),
    ordinalSuffixRegex = "st|nd|rd|th",
    todayWords = listOf("today"),
    tomorrowWords = listOf("tomorrow"),
    nextWords = listOf("next"),
    onWords = listOf("on"),
    atWords = listOf("at"),
    amWords = listOf("am", "a.m.", "a.m"),
    pmWords = listOf("pm", "p.m.", "p.m"),
    noonWords = listOf("noon", "midday"),
    midnightWords = listOf("midnight"),
    timeUnitWords = listOf("o'clock", "oclock"),
    dateOrder = DateOrder.MONTH_DAY,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("on", "at", "for", "to"),
  )

  /** "mañana" means both "tomorrow" and "morning" in Spanish; treated as "tomorrow" here since
   * that's the far more common quick-add phrasing - a known v1 ambiguity. */
  val spanish = QuickAddVocabulary(
    languageTag = "es",
    everyWords = listOf("cada", "todos los", "todas las"),
    dailyUnitWords = listOf("dia", "dias", "día", "días"),
    weeklyUnitWords = listOf("semana", "semanas"),
    monthlyUnitWords = listOf("mes", "meses"),
    yearlyUnitWords = listOf("ano", "anos", "año", "años"),
    dailyAdverbs = listOf("diariamente", "a diario"),
    weeklyAdverbs = listOf("semanalmente"),
    monthlyAdverbs = listOf("mensualmente"),
    yearlyAdverbs = listOf("anualmente"),
    workdayWords = listOf("dia laborable", "dias laborables", "día laborable", "días laborables"),
    ordinalSuffixRegex = "º|ª",
    todayWords = listOf("hoy"),
    tomorrowWords = listOf("manana", "mañana"),
    nextWords = listOf("proximo", "proxima", "próximo", "próxima"),
    onWords = listOf("el", "la"),
    atWords = listOf("a las", "a la"),
    amWords = listOf("am", "a.m.", "de la manana", "de la mañana"),
    pmWords = listOf("pm", "p.m.", "de la tarde", "de la noche"),
    noonWords = listOf("mediodia", "mediodía"),
    midnightWords = listOf("medianoche"),
    timeUnitWords = listOf("horas", "hora"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = listOf("de"),
    connectorWords = listOf("el", "la", "a", "para"),
  )

  val french = QuickAddVocabulary(
    languageTag = "fr",
    everyWords = listOf("chaque", "tous les", "toutes les"),
    dailyUnitWords = listOf("jour", "jours"),
    weeklyUnitWords = listOf("semaine", "semaines"),
    monthlyUnitWords = listOf("mois"),
    yearlyUnitWords = listOf("an", "ans", "annee", "annees", "année", "années"),
    dailyAdverbs = listOf("quotidiennement"),
    weeklyAdverbs = listOf("hebdomadairement"),
    monthlyAdverbs = listOf("mensuellement"),
    yearlyAdverbs = listOf("annuellement"),
    workdayWords = listOf("jour ouvre", "jours ouvres", "jour ouvré", "jours ouvrés"),
    ordinalSuffixRegex = "er|eme|ème|e",
    todayWords = listOf("aujourd'hui", "aujourdhui"),
    tomorrowWords = listOf("demain"),
    nextWords = listOf("prochain", "prochaine"),
    onWords = listOf("le", "la"),
    // Deliberately just "à" (accented), not bare "a" - the latter is French's extremely common
    // "has" verb form (il/elle a), which would false-positive-match all over ordinary text.
    atWords = listOf("à"),
    amWords = listOf("am", "du matin"),
    pmWords = listOf("pm", "de l'apres-midi", "de l'après-midi", "du soir"),
    noonWords = listOf("midi"),
    midnightWords = listOf("minuit"),
    timeUnitWords = listOf("heures", "heure", "h"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("le", "la", "à", "pour"),
  )

  /** "morgen" means both "tomorrow" and "morning" in German; treated as "tomorrow" here, same
   * known v1 ambiguity as Spanish "mañana". */
  val german = QuickAddVocabulary(
    languageTag = "de",
    everyWords = listOf("jeden", "jede", "jedes", "alle"),
    dailyUnitWords = listOf("tag", "tage"),
    weeklyUnitWords = listOf("woche", "wochen"),
    monthlyUnitWords = listOf("monat", "monate"),
    yearlyUnitWords = listOf("jahr", "jahre"),
    dailyAdverbs = listOf("taglich", "täglich"),
    weeklyAdverbs = listOf("wochentlich", "wöchentlich"),
    monthlyAdverbs = listOf("monatlich"),
    yearlyAdverbs = listOf("jahrlich", "jährlich"),
    workdayWords = listOf("wochentag", "wochentage"),
    ordinalSuffixRegex = "\\.",
    todayWords = listOf("heute"),
    tomorrowWords = listOf("morgen"),
    nextWords = listOf("nachsten", "nachste", "nächsten", "nächste"),
    onWords = listOf("am"),
    atWords = listOf("um"),
    amWords = emptyList(),
    pmWords = emptyList(),
    noonWords = listOf("mittag", "mittags"),
    midnightWords = listOf("mitternacht"),
    timeUnitWords = listOf("uhr"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("am", "um", "fur", "für"),
  )

  val portuguese = QuickAddVocabulary(
    languageTag = "pt",
    everyWords = listOf("todo", "toda", "todos os", "todas as", "cada"),
    dailyUnitWords = listOf("dia", "dias"),
    weeklyUnitWords = listOf("semana", "semanas"),
    monthlyUnitWords = listOf("mes", "meses", "mês"),
    yearlyUnitWords = listOf("ano", "anos"),
    dailyAdverbs = listOf("diariamente"),
    weeklyAdverbs = listOf("semanalmente"),
    monthlyAdverbs = listOf("mensalmente"),
    yearlyAdverbs = listOf("anualmente"),
    workdayWords = listOf("dia util", "dias uteis", "dia útil", "dias úteis"),
    ordinalSuffixRegex = "º|ª",
    todayWords = listOf("hoje"),
    tomorrowWords = listOf("amanha", "amanhã"),
    nextWords = listOf("proximo", "proxima", "próximo", "próxima"),
    onWords = listOf("no", "na"),
    // Deliberately just "às" (accented contraction), not bare "as" - the latter is Portuguese's
    // common feminine plural article ("the"), which would false-positive-match constantly.
    atWords = listOf("às"),
    amWords = listOf("am", "da manha", "da manhã"),
    pmWords = listOf("pm", "da tarde", "da noite"),
    noonWords = listOf("meio-dia", "meio dia"),
    midnightWords = listOf("meia-noite", "meia noite"),
    timeUnitWords = listOf("horas", "hora"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = listOf("de"),
    connectorWords = listOf("no", "na", "às", "para"),
  )

  val italian = QuickAddVocabulary(
    languageTag = "it",
    everyWords = listOf("ogni", "tutti i", "tutte le"),
    dailyUnitWords = listOf("giorno", "giorni"),
    weeklyUnitWords = listOf("settimana", "settimane"),
    monthlyUnitWords = listOf("mese", "mesi"),
    yearlyUnitWords = listOf("anno", "anni"),
    dailyAdverbs = listOf("giornalmente", "quotidianamente"),
    weeklyAdverbs = listOf("settimanalmente"),
    monthlyAdverbs = listOf("mensilmente"),
    yearlyAdverbs = listOf("annualmente"),
    workdayWords = listOf("giorno feriale", "giorni feriali"),
    ordinalSuffixRegex = "°|ª",
    todayWords = listOf("oggi"),
    tomorrowWords = listOf("domani"),
    nextWords = listOf("prossimo", "prossima"),
    onWords = listOf("il", "la"),
    atWords = listOf("alle", "alla"),
    amWords = listOf("am", "di mattina"),
    pmWords = listOf("pm", "del pomeriggio", "di sera"),
    noonWords = listOf("mezzogiorno"),
    midnightWords = listOf("mezzanotte"),
    timeUnitWords = listOf("ore", "ora"),
    dateOrder = DateOrder.DAY_MONTH,
    dayMonthConnectors = emptyList(),
    connectorWords = listOf("il", "la", "alle", "alla", "per"),
  )
}
