package com.elementary.tasks.core.utils

/**
 * Copyright 2016 Nazar Suhovich
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
object PrefsConstants {

    const val PREFS_NAME = "prefs_six"
    const val EVENTS_CALENDAR = "events_cal"
    const val AUTO_CHECK_FOR_EVENTS = "auto_events"
    const val AUTO_CHECK_FOR_EVENTS_INTERVAL = "auto_events_interval"
    const val APP_THEME = "theme_"
    const val APP_THEME_COLOR = "theme_color"
    const val DRIVE_USER = "ggl_user"
    const val TASKS_USER = "gtl_user"
    const val SCREEN = "screen"
    const val MAP_TYPE = "new_map_type"
    const val MAP_STYLE = "new_map_style"
    const val LOCATION_RADIUS = "radius"
    const val TRACKING_NOTIFICATION = "tracking_notification"
    const val VIBRATION_STATUS = "vibration_status"
    const val SILENT_SOUND = "sound_status"
    const val WAKE_STATUS = "wake_status"
    const val INFINITE_SOUND = "infinite_sound"
    const val SILENT_SMS = "silent_sms"
    const val CONTACT_BIRTHDAYS = "use_contacts"
    const val BIRTHDAY_REMINDER = "birthdays_reminder"
    const val START_DAY = "start_day"
    const val DAYS_TO_BIRTHDAY = "days_to"
    const val DELAY_TIME = "delay_time"
    const val EVENT_DURATION = "event_duration"
    const val EXPORT_TO_CALENDAR = "export_to_calendar"
    const val CALENDAR_ID = "cal_id"
    const val AUTO_CHECK_BIRTHDAYS = "birthdays_auto_scan"
    const val LED_STATUS = "led_status"
    const val LED_COLOR = "led_color"
    const val MARKER_STYLE = "marker_style"
    const val INFINITE_VIBRATION = "infinite_vibration"
    const val AUTO_BACKUP = "auto_backup"
    const val DATA_BACKUP = "data_backup"
    const val AUTO_BACKUP_INTERVAL = "auto_backup_interval"
    const val SMART_FOLD = "smart_fold"
    const val NOTIFICATION_REPEAT = "notification_repeat"
    const val NOTIFICATION_REPEAT_INTERVAL = "notification_repeat_interval"
    const val WEAR_NOTIFICATION = "wear_notification"
    const val WIDGET_BIRTHDAYS = "widget_birthdays"
    const val NOTIFICATION_REMOVE = "notification_remove"
    const val BIRTH_COLOR = "birth_color"
    const val TODAY_COLOR = "today_color"
    const val STATUS_BAR_ICON = "status_icon"
    const val STATUS_BAR_NOTIFICATION = "status_notification"
    const val TRACK_TIME = "tracking_time"
    const val TRACK_DISTANCE = "tracking_distance"
    const val NOTE_TEXT_SIZE = "text_size"
    const val QUICK_NOTE_REMINDER = "quick_note_reminder"
    const val QUICK_NOTE_REMINDER_TIME = "quick_note_reminder_time"
    const val VOICE_LOCALE = "voice_locale"
    const val TIME_MORNING = "time_morning"
    const val TIME_DAY = "time_day"
    const val TIME_EVENING = "time_evening"
    const val TIME_NIGHT = "time_night"
    const val EXPORT_TO_STOCK = "export_to_stock"
    const val APPLICATION_AUTO_LAUNCH = "application_auto_launch"
    const val REMINDERS_IN_CALENDAR = "reminders_in_calendar"
    const val REMINDER_COLOR = "reminder_color"
    const val TIME_FORMAT = "new_hour_format"
    const val UNLOCK_DEVICE = "unlock_device"
    const val CALENDAR_FEATURE_TASKS = "feature_tasks"
    const val MISSED_CALL_REMINDER = "missed_call_reminder"
    const val MISSED_CALL_TIME = "missed_call_time"
    const val VOLUME = "reminder_volume"
    const val QUICK_SMS = "quick_sms"
    const val FOLLOW_REMINDER = "follow_reminder"
    const val TTS = "tts_enabled"
    const val TTS_LOCALE = "tts_locale"
    const val ITEM_PREVIEW = "item_preview"
    const val UI_CHANGED = "ui_changed"
    const val CALENDAR_IMAGE = "calendar_image"
    const val EXPORT_SETTINGS = "export_settings"
    const val CUSTOM_SOUND = "custom_sound"
    const val BIRTHDAY_PERMANENT = "birthday_permanent"
    const val REMINDER_IMAGE = "reminder_image"
    const val REMINDER_IMAGE_BLUR = "reminder_image_blur"
    const val SYSTEM_VOLUME = "system_volume"
    const val SOUND_STREAM = "sound_stream"
    const val INCREASING_VOLUME = "increasing_volume"
    const val AUTO_CALL = "auto_calls"
    const val GCM_ENABLED = "gcm_enabled"
    const val BETA_KEY = "beta_key"
    const val RATE_COUNT = "rate_count"
    const val USER_LOGGED = "user_logged"
    const val LIVE_CONVERSATION = "live_conversation"
    const val AUTO_SAVE = "auto_save"
    const val REMEMBER_NOTE_COLOR = "remember_note_color"
    const val LAST_NOTE_COLOR = "last_note_color"
    const val NOTE_COLOR_OPACITY = "note_color_opacity"
    const val REMINDER_TYPE = "notification_type"
    const val DROPBOX_UID = "dropbox_uid"
    const val DROPBOX_TOKEN = "dropbox_token"
    const val TELL_ABOUT_EVENT = "tell_about_event"
    const val APP_LANGUAGE = "app_language"
    const val IGNORE_WINDOW_TYPE = "ignore_window_type"
    const val PIN_CODE = "pin_code"
    const val USE_FINGERPRINT = "use_finger"
    const val HOME_PAGE = "home_page"
    const val TWO_COLS = "two_cols"
    const val ALLOW_SMS_AND_CALL = "allow_sms_and_call"

    const val REMINDER_CHANGED = "reminder_changed"
    const val LAST_USED_REMINDER = "last_reminder"
    const val LAST_LIST = "last_list"
    const val NOTES_ORDER = "notes_ordering"
    const val NOTES_LIST_STYLE = "notes_style"
    const val TASKS_ORDER = "tasks_ordering"
    const val RATE_SHOW = "show_rate"
    const val APP_RUNS_COUNT = "app_runs"

    // birthdays reminder notification constants
    const val BIRTHDAY_USE_GLOBAL = "use_global"
    const val BIRTHDAY_VIBRATION_STATUS = "birthday_vibration_status"
    const val BIRTHDAY_SILENT_STATUS = "birthday_sound_status"
    const val BIRTHDAY_WAKE_STATUS = "birthday_wake_status"
    const val BIRTHDAY_INFINITE_SOUND = "birthday_infinite_sound"
    const val BIRTHDAY_LED_STATUS = "birthday_led_status"
    const val BIRTHDAY_LED_COLOR = "birthday_led_color"
    const val BIRTHDAY_INFINITE_VIBRATION = "birthday_infinite_vibration"
    const val BIRTHDAY_SOUND_FILE = "birthday_sound_file"
    const val BIRTHDAY_REMINDER_TIME = "reminder_hour"
    const val BIRTHDAY_TTS = "birthday_tts"
    const val BIRTHDAY_TTS_LOCALE = "birthday_tts_locale"

    const val IS_CREATE_SHOWN = "create_showcase"
    const val IS_CALENDAR_SHOWN = "calendar_showcase"
    const val IS_LIST_SHOWN = "list_showcase"
}
