package com.github.naz013.ui.common.compose

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.compositeOver

const val DisabledAlpha = 0.38f

val primaryLight = Color(0xFF4F6703)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD0EE82)
val onPrimaryContainerLight = Color(0xFF151F00)
val secondaryLight = Color(0xFF6C5C43)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF6DFBF)
val onSecondaryContainerLight = Color(0xFF251A06)
val tertiaryLight = Color(0xFF7E5538)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDCC6)
val onTertiaryContainerLight = Color(0xFF301401)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A14)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF221A14)
val surfaceVariantLight = Color(0xFFF9DEC8)
val onSurfaceVariantLight = Color(0xFF554334)
val outlineLight = Color(0xFF80756C)
val outlineVariantLight = Color(0xFFDCC2AD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372F28)
val inverseOnSurfaceLight = Color(0xFFFDEEE3)
val inversePrimaryLight = Color(0xFFB4D269)
val surfaceDimLight = Color(0xFFE6D7CD)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E8)
val surfaceContainerLight = Color(0xFFFBEBE0)
val surfaceContainerHighLight = Color(0xFFF5E5DB)
val surfaceContainerHighestLight = Color(0xFFEFE0D5)

val primaryDark = Color(0xFFB4D269)
val onPrimaryDark = Color(0xFF273500)
val primaryContainerDark = Color(0xFF3A4D00)
val onPrimaryContainerDark = Color(0xFFD0EE82)
val secondaryDark = Color(0xFFD9C4A5)
val onSecondaryDark = Color(0xFF3B2E19)
val secondaryContainerDark = Color(0xFF53452D)
val onSecondaryContainerDark = Color(0xFFF6DFBF)
val tertiaryDark = Color(0xFFF1BB98)
val onTertiaryDark = Color(0xFF49280F)
val tertiaryContainerDark = Color(0xFF633E23)
val onTertiaryContainerDark = Color(0xFFFFDCC6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF19120C)
val onBackgroundDark = Color(0xFFEFE0D5)
val surfaceDark = Color(0xFF19120C)
val onSurfaceDark = Color(0xFFEFE0D5)
val surfaceVariantDark = Color(0xFF554334)
val onSurfaceVariantDark = Color(0xFFDCC2AD)
val outlineDark = Color(0xFF9B8E85)
val outlineVariantDark = Color(0xFF554334)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFE0D5)
val inverseOnSurfaceDark = Color(0xFF372F28)
val inversePrimaryDark = Color(0xFF4F6703)
val surfaceDimDark = Color(0xFF19120C)
val surfaceBrightDark = Color(0xFF403730)
val surfaceContainerLowestDark = Color(0xFF130D07)
val surfaceContainerLowDark = Color(0xFF221A14)
val surfaceContainerDark = Color(0xFF261E18)
val surfaceContainerHighDark = Color(0xFF312822)
val surfaceContainerHighestDark = Color(0xFF3C332C)

// Expressive "Fixed" roles are theme-independent by M3 spec — same value in light and dark schemes.
val primaryFixed = Color(0xFFD0EE82)
val primaryFixedDim = Color(0xFFB4D269)
val onPrimaryFixed = Color(0xFF151F00)
val onPrimaryFixedVariant = Color(0xFF3A4D00)
val secondaryFixed = Color(0xFFF6DFBF)
val secondaryFixedDim = Color(0xFFD9C4A5)
val onSecondaryFixed = Color(0xFF251A06)
val onSecondaryFixedVariant = Color(0xFF53452D)
val tertiaryFixed = Color(0xFFFFDCC6)
val tertiaryFixedDim = Color(0xFFF1BB98)
val onTertiaryFixed = Color(0xFF301401)
val onTertiaryFixedVariant = Color(0xFF633E23)

fun Int.toColor(): Color = Color(this)

fun Color.withAlpha(alpha: Float): Color = copy(alpha = alpha)

fun Color.blendWithAlpha(base: Color, alpha: Float): Color {
  return withAlpha(alpha = alpha).compositeOver(background = base)
}
