package com.elementary.tasks.core.utils.params

object PrefsConstants {

  const val PREFS_NAME = "prefs_six"

  @Deprecated("Should not use")
  const val EVENTS_CALENDAR = "events_cal"
  const val AUTO_CHECK_FOR_EVENTS = "auto_events"
  const val AUTO_CHECK_FOR_EVENTS_INTERVAL = "auto_events_interval"
  const val DRIVE_USER = "ggl_user"
  const val TASKS_USER = "gtl_user"
  const val MAP_TYPE = "new_map_type"
  const val MAP_STYLE = "new_map_style"
  const val LOCATION_RADIUS = "radius"
  const val TRACKING_NOTIFICATION = "tracking_notification"
  const val VIBRATION_STATUS = "vibration_status"
  const val CONTACT_BIRTHDAYS = "use_contacts"
  const val BIRTHDAY_REMINDER = "birthdays_reminder"
  const val START_DAY = "start_day"
  const val DAYS_TO_BIRTHDAY = "days_to"
  const val DELAY_TIME = "delay_time"
  const val EVENT_DURATION = "event_duration"
  const val EXPORT_TO_CALENDAR = "export_to_calendar"

  @Deprecated("Should not use")
  const val CALENDAR_ID = "cal_id"
  const val CALENDAR_IDS = "calendar_ids"
  const val DEFAULT_CALENDAR_ID = "default_calendar_id"
  const val AUTO_CHECK_BIRTHDAYS = "birthdays_auto_scan"
  const val LED_STATUS = "led_status"
  const val LED_COLOR = "led_color"
  const val MARKER_STYLE = "marker_style"
  const val INFINITE_VIBRATION = "infinite_vibration"
  const val NOTIFICATION_REPEAT = "notification_repeat"
  const val NOTIFICATION_REPEAT_INTERVAL = "notification_repeat_interval"
  const val WEAR_NOTIFICATION = "wear_notification"
  const val WIDGET_BIRTHDAYS = "widget_birthdays"
  const val BIRTH_COLOR = "birth_color"
  const val TODAY_COLOR = "today_color"
  const val STATUS_BAR_ICON = "status_icon"
  const val STATUS_BAR_NOTIFICATION = "status_notification"
  const val TRACK_TIME = "tracking_time"
  const val EXPORT_TO_STOCK = "export_to_stock"
  const val REMINDER_COLOR = "reminder_color"
  const val TIME_FORMAT = "new_hour_format"
  const val BIRTHDAY_PERMANENT = "birthday_permanent"
  const val RATE_COUNT = "rate_count"
  const val USER_LOGGED = "user_logged"

  const val REMEMBER_NOTE_COLOR = "remember_note_color"
  const val REMEMBER_NOTE_FONT_SIZE = "remember_note_font_size"
  const val REMEMBER_NOTE_FONT_STYLE = "remember_note_font_style"
  const val LAST_NOTE_COLOR = "last_note_color"
  const val LAST_NOTE_FONT_SIZE = "last_note_font_size"
  const val LAST_NOTE_FONT_STYLE = "last_note_font_style"
  const val NOTE_COLOR_OPACITY = "note_color_opacity"

  const val DROPBOX_TOKEN = "dropbox_token"
  const val APP_LANGUAGE = "app_language"
  const val REMINDER_CREATOR_PARAMS = "reminder_creator_params"

  const val PIN_CODE = "pin_code"
  const val USE_FINGERPRINT = "use_finger"
  const val SHUFFLE_PIN_VIEW = "shuffle_pin_view"

  const val ALLOW_SMS_AND_CALL = "allow_sms_and_call"
  const val MOVE_TO_TRASH = "move_to_trash"
  const val DEFAULT_PRIORITY = "default_priority"
  const val BIRTHDAY_PRIORITY = "birthday_priority"
  const val DO_NOT_DISTURB_ENABLED = "do_not_disturb_enabled"
  const val DO_NOT_DISTURB_FROM = "do_not_disturb_from"
  const val DO_NOT_DISTURB_TO = "do_not_disturb_to"
  const val DO_NOT_DISTURB_IGNORE = "do_not_disturb_ignore"
  const val DO_NOT_DISTURB_ACTION = "do_not_disturb_action"
  const val NOTE_PALETTE = "note_palette"
  const val AUTO_BACKUP_STATE = "auto_backup_state"
  const val NIGHT_MODE = "night_mode"
  const val PRIVACY_SHOWED = "privacy_showed"
  const val TO_BIRTHDAY_DAYS = "to_birthday_days"
  const val DYNAMIC_COLORS = "dynamic_colors_13"
  const val ANALYTICS_ENABLED = "analytics_enabled"
  const val METRIC_SYSTEM = "metric_system"

  const val SALE_MESSAGE = "sale_message_json_v2"
  const val INTERNAL_MESSAGE = "internal_message_json_v1"

  const val REMINDER_CHANGED = "reminder_changed"
  const val NOTES_ORDER = "notes_ordering"
  const val NOTES_LIST_STYLE = "notes_style"
  const val RATE_SHOW = "show_rate"
  const val APP_RUNS_COUNT = "app_runs"

  const val LAST_VERSION_CODE = "last_version_code"

  // birthdays reminder notification constants
  const val BIRTHDAY_USE_GLOBAL = "use_global"
  const val BIRTHDAY_VIBRATION_STATUS = "birthday_vibration_status"
  const val BIRTHDAY_LED_STATUS = "birthday_led_status"
  const val BIRTHDAY_LED_COLOR = "birthday_led_color"
  const val BIRTHDAY_INFINITE_VIBRATION = "birthday_infinite_vibration"
  const val BIRTHDAY_REMINDER_TIME = "reminder_hour"

  const val IS_PRESET_INIT = "preset_init"
  const val IS_DEFAULT_PRESET_INIT = "preset_init_default"

  const val REMINDERS_CREATED_COUNT = "reminders_created_count"
  const val REVIEW_DIALOG_SHOWN = "review_dialog_shown"

  const val PRIVACY_POLICY_URL = "privacy_url"
  const val TERMS_URL = "terms_url"

  const val WORKER_NETWORK_TYPE = "worker_network_type"
  const val OCCURRENCE_MIGRATED = "occurrence_migrated"
  const val OCCURRENCE_COUNT_REMINDERS = "occurrence_count_reminders"
  const val OCCURRENCE_COUNT_BIRTHDAYS = "occurrence_count_birthdays"
}
