package com.github.naz013.repository.table

enum class Table(val tableName: String) {
  Birthday("Birthday"),
  RecentQuery("RecentQuery"),
  RecurPreset("RecurPreset"),
  UsedTime("UsedTime"),
  CalendarEvent("CalendarEvent"),
  ReminderGroup("ReminderGroup"),
  Reminder("Reminder"),
  ReminderV2("ReminderV2"),
  GroupV2("GroupV2"),
  WorkflowRule("WorkflowRule"),
  WorkflowTemplate("WorkflowTemplate"),
  Place("Place"),
  Note("Note"),
  ImageFile("ImageFile"),
  GoogleTaskList("GoogleTaskList"),
  GoogleTask("GoogleTask"),
  RemoteFileMetadata("RemoteFileMetadata"),
  EventOccurrence("EventOccurrence"),
  EventHistory("EventHistory"),
  Tag("Tag"),
  TagAssignment("TagAssignment"),
  Holiday("Holiday"),
}
