name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create file
      run: cat /home/runner/work/reminder-kotlin/reminder-kotlin/app/google-services.json | base64
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES }}
      run: echo $DATA > /home/runner/work/reminder-kotlin/reminder-kotlin/app/google-services.json

    - name: Voice Unit Test
      run: ./gradlew :voice-engine-ktx:test
    - name: Upload Voice Test Reports Folder
      uses: actions/upload-artifact@v3
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: voice_reports
        path: voice-engine-ktx/build/test-results # path to where the xml test results are stored

    - name: Unit Test
      run: ./gradlew testProDebugUnitTest
    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v3
      if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
      with:
        name: reports
        path: app/build/test-results # path to where the xml test results are stored
